name: "Precompile Assets"

inputs:
  github_sha:
    default: ""
    description: "Github sha to store in the cache key"
    required: false
    type: string
  working-directory:
    description: "Working directory to restore/install"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Restore precompiled assets cache, if exists
      uses: actions/cache@v4
      id: assets-cache
      with:
        path: |
          ${{ inputs.working-directory == '' && './**' || inputs.working-directory }}/public/assets
          ${{ inputs.working-directory == '' && './**' || inputs.working-directory }}/public/vite-test
          ${{ inputs.working-directory == '' && './**' || inputs.working-directory }}/app/assets/builds
        key: ${{ runner.os }}-precompiled-assets-${{ inputs.github_sha || github.sha }}-dir-${{ inputs.working-directory }}

    - name: Compile assets
      if: ${{ steps.assets-cache.outputs.cache-hit != 'true' }}
      run: NODE_ENV=development bundle exec rake assets:precompile
      shell: bash
      working-directory: ${{ inputs.working-directory }}
