name: "Precompile Assets"

inputs:
  install-dependencies:
    description: "Whether or not to install dependencies"
    default: false
    required: false
  working-directory:
    description: "Working directory to restore/install"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Restore precompiled assets cache, if exists
      uses: actions/cache@v3
      id: assets-cache
      with:
        path: |
          ${{ inputs.working-directory == '' && './**' || inputs.working-directory }}/public/assets
          ${{ inputs.working-directory == '' && './**' || inputs.working-directory }}/public/vite-test
          ${{ inputs.working-directory == '' && './**' || inputs.working-directory }}/app/assets/builds
        key: ${{ runner.os }}-precompiled-assets-${{ github.sha }}-dir-${{ inputs.working-directory }}

    - name: Compile assets
      if: ${{ steps.assets-cache.outputs.cache-hit != 'true' || inputs.install-dependencies == 'true' }}
      run: NODE_ENV=development bundle exec rake assets:precompile
      shell: bash
      working-directory: ${{ inputs.working-directory }}
