name: Slack Notification

inputs:
  custom_payload:
    default: null
    description: "Custom payload to send to Slack"
    required: false
  send_all_notifications:
    description: "Send the notification regardless of success or failure"
    default: false
    required: false
    type: boolean
  webhook_url:
    description: "Slack webhook url to send the notification to"
    required: true

runs:
  using: "composite"
  steps:
    - uses: technote-space/workflow-conclusion-action@v3

    - name: Determine Status
      uses: haya14busa/action-cond@v1
      id: status
      with:
        cond: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        if_true: "success"
        if_false: "failure"

    - name: Determine Fields
      uses: haya14busa/action-cond@v1
      id: fields
      with:
        cond: ${{ github.event_name != 'pull_request' }}
        if_true: "repo,commit,eventName,workflow,ref"
        if_false: "repo,commit,eventName,workflow,pullRequest,ref"

    - name: Generic Slack Notification
      if: ${{ (inputs.send_all_notifications == 'true' || steps.status.outputs.value == 'failure') && custom_payload == null }}
      uses: 8398a7/action-slack@v3
      with:
        fields: ${{ steps.fields.outputs.value }}
        status: ${{ steps.status.outputs.value }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}

    - name: Custom Slack Notification
      if: ${{ (inputs.send_all_notifications == 'true' || steps.status.outputs.value == 'failure') && custom_payload != null  }}
      uses: 8398a7/action-slack@v3
      with:
        custom_payload: |
          ${{ inputs.custom_payload }}
        fields: ${{ steps.fields.outputs.value }}
        status: ${{ steps.status.outputs.value }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
