name: "Setup Node"
inputs:
  node-version:
    description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0."
    required: true
  install-dependencies:
    description: "Whether or not to install dependencies"
    default: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Get yarn cache directory path
      if: ${{ inputs.install-dependencies == 'true' }}
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Restore yarn cache, if exists
      uses: actions/cache@v3
      if: ${{ inputs.install-dependencies == 'true' }}
      id: yarn-cache
      with:
        path: |
          **/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-

    - name: Install yarn dependencies
      if: ${{ inputs.install-dependencies == 'true' && steps.yarn-cache.outputs.cache-hit != 'true' }}
      run: yarn --prefer-offline --frozen-lockfile
      shell: bash
