name: "Setup Node"
description: "Setup Node for the repository"

inputs:
  find-node-version:
    default: "false"
    description: "Whether to find the node version by using the .tool-versions file"
    required: false
  node-version:
    description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0."
    required: false
  enable-corepack:
    description: "Enable Corepack"
    default: "false"
    required: false
  npm_access_token:
    description: "Access token for downloading private npm packages from @buoysoftware"
    required: false
  github_packages_token:
    description: "Access token for downloading private npm packages from @buoysoftware"
    required: false
  install-dependencies:
    description: "Whether or not to install dependencies"
    default: "true"
    required: false
  working-directory:
    description: "Working directory to restore/install"
    default: ""
    required: false

runs:
  using: "composite"

  steps:
    - name: Ensure one of node-version or find-node-version is provided
      if: ${{ inputs.node-version == '' && inputs.find-node-version == 'false' }}
      run: |
        echo "Error: One of node-version or find-node-version must be provided"
        echo "node-version: ${{ inputs.node-version }}"
        echo "find-node-version: ${{ inputs.find-node-version }}"
        exit 1
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    # Could add more logic to find the node version from other files like .nvmrc, .node-version, etc.
    - name: Find node version when find-node-version is provided
      if: ${{ inputs.find-node-version == 'true' }}
      id: find-node-version
      run: echo "v=$(grep 'nodejs' .tool-versions | awk '{print $2}')" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.find-node-version.outputs.v || inputs.node-version }}

    - name: Enable Corepack
      if: ${{ inputs.enable-corepack == 'true' }}
      run: corepack enable
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Get yarn cache directory path
      if: ${{ inputs.install-dependencies == 'true' }}
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Restore yarn cache, if exists
      uses: actions/cache@v3
      if: ${{ inputs.install-dependencies == 'true' }}
      id: yarn-cache
      with:
        path: |
          ${{ inputs.working-directory == '' && './**' || inputs.working-directory }}/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node-${{ steps.find-node-version.outputs.v || inputs.node-version }}-dir-${{ inputs.working-directory }}-yarn-${{ hashFiles(format('{0}/yarn.lock', inputs.working-directory == '' && './**' || inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-node-${{ steps.find-node-version.outputs.v || inputs.node-version }}-dir-${{ inputs.working-directory }}-yarn-

    - name: Authenticate with private NPM package
      if: ${{ inputs.npm_access_token }}
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm_access_token }}" > ~/.npmrc
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Authenticate with Github Packages
      if: ${{ inputs.github_packages_token }}
      run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.github_packages_token }}" > ~/.npmrc && echo "@buoysoftware:registry=https://npm.pkg.github.com/" >> .npmrc
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Install yarn dependencies
      if: ${{ inputs.install-dependencies == 'true' && steps.yarn-cache.outputs.cache-hit != 'true' }}
      run: yarn --prefer-offline --frozen-lockfile --ignore-scripts
      shell: bash
      working-directory: ${{ inputs.working-directory }}
