name: "Setup Node"
inputs:
  node-version:
    description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0."
    required: true
  install-dependencies:
    description: "Whether or not to install dependencies"
    default: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      id: setup-node
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.install-dependencies == 'true' && 'yarn' }}

    - name: Get yarn cache directory path
      if: ${{ inputs.install-dependencies == 'true' }}
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install yarn dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      run: yarn --prefer-offline --frozen-lockfile --immutable
      shell: bash
