name: Setup repo

inputs:
  database_name:
    description: Database name to create
    required: true
    type: string
  extra_rake_tasks:
    default: ""
    description: Run additional rake tasks when creating database, separate with spaces
    required: false
    type: string
  node_version_file:
    default: ".tool-versions"
    description: Node version file (.tool-versions, .nvmrc)
    required: false
    type: string
  npm_access_token:
    description: Access token for downloading private npm packages from @buoysoftware
    required: false
    type: string
  personal_access_token:
    description: Personal access token generated for the repository
    required: true
    type: string
  repo:
    description: Full repository name (Org/Repo)
    required: true
    type: string
  short_git_sha:
    default: ""
    description: Short git sha, leave empty for current branch
    required: false
    type: string
  working_directory:
    default: "."
    description: Desired working directory for the repository
    required: false
    type: string

runs:
  using: "composite"

  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        path: ${{ inputs.working_directory }}
        repository: ${{ inputs.repo }}
        token: ${{ inputs.personal_access_token }}

    - name: Checkout repo short git sha (if present)
      if: ${{ inputs.short_git_sha != '' }}
      run: git fetch --tags && git checkout ${{ inputs.short_git_sha }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Install Vips
      if: endsWith(inputs.repo, 'BuoyRails')
      run: sudo apt-get update && sudo apt-get install -y libvips
      shell: bash

    - name: Set up environment variables for repo
      run: cp .env.sample .env
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Install Ruby for repo
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working_directory }}

    - name: Get node version
      id: repo_node_vers
      run: echo "v=$(grep 'nodejs' ${{ inputs.node_version_file }} | awk '{print $2}')" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Install Node
      uses: BuoySoftware/github-actions/setup-node@main
      with:
        node-version: ${{ steps.repo_node_vers.outputs.v }}
        npm_access_token: ${{ inputs.npm_access_token }}
        working-directory: ${{ inputs.working_directory }}

    - name: bundle check for repo
      run: bundle check
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Precompile test assets
      uses: BuoySoftware/github-actions/precompile-assets@main
      with:
        working-directory: ${{ inputs.working_directory }}

    - name: Create, load and seed repo database
      env:
        DB_TEST_DATABASE: ${{ inputs.database_name }}
      run: bundle exec rake db:drop db:create db:schema:load ${{ inputs.extra_rake_tasks }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
