name: Setup repo

inputs:
  env_vars:
    default: ""
    description: Environment variables to set
    required: false
    type: string
  extra_rake_tasks:
    default: ""
    description: Run additional rake tasks when creating database, separate with spaces
    required: false
    type: string
  github_packages_token:
    description: Access token for downloading private github packages from @buoysoftware
    required: false
    type: string
  node_version_file:
    default: ".tool-versions"
    description: Node version file (.tool-versions, .nvmrc)
    required: false
    type: string
  personal_access_token:
    description: Personal access token generated for the repository
    required: true
    type: string
  ref:
    default: ""
    description: The branch, tag or SHA to checkout, ie `v1.2.0`
    required: false
    type: string
  repo:
    description: Full repository name (Org/Repo)
    required: true
    type: string
  working_directory:
    default: "."
    description: Desired working directory for the repository
    required: false
    type: string

runs:
  using: "composite"

  steps:
    - name: Determine ref to checkout
      id: ref_check
      run: |
        ref="${{ inputs.ref }}"
        if [[ "$ref" =~ ^[a-f0-9]{40}$ ]]; then
          echo "✅ Full SHA detected"
          echo "ref_to_checkout=$ref" >> $GITHUB_OUTPUT
        elif [[ "$ref" =~ ^[a-f0-9]{7,39}$ ]]; then
          echo "⚠️ Short SHA detected, will checkout main first"
          echo "ref_to_checkout=main" >> $GITHUB_OUTPUT
        else
          echo "🔖 Tag or branch detected"
          echo "ref_to_checkout=$ref" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        path: ${{ inputs.working_directory }}
        ref: ${{ steps.ref_check.outputs.ref_to_checkout }}
        repository: ${{ inputs.repo }}
        token: ${{ inputs.personal_access_token }}

    - name: If needed, checkout the short SHA manually
      if: ${{ steps.ref_check.outputs.ref_to_checkout != inputs.ref }}
      run: |
        echo "🔄 Checking out ref: ${{ inputs.ref }}"
        git fetch origin
        git checkout "${{ inputs.ref }}"
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Validate the checked out ref
      if: ${{ inputs.ref != '' }}
      run: |
        input_ref="${{ inputs.ref }}"

        echo "🔍 Resolving input ref: $input_ref"
        resolved_ref=$(git rev-parse "${input_ref}^{}" 2>/dev/null || true)

        if [ -z "$resolved_ref" ]; then
          echo "❌ Could not resolve ref '$input_ref'."
          git show-ref
          exit 1
        fi

        current_head=$(git rev-parse HEAD)

        if [[ "$current_head" != "$resolved_ref" ]]; then
          echo "❌ Checked out ref does not match input ref."
          echo "Current HEAD: $current_head"
          echo "Expected ref: $resolved_ref"
          exit 1
        fi

        echo "✅ Ref '$input_ref' correctly checked out as '$resolved_ref'"
        echo "repo_sha=$resolved_ref" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Install Vips
      if: endsWith(inputs.repo, 'BuoyRails')
      run: sudo apt-get update && sudo apt-get install -y libvips
      shell: bash

    - name: Set up environment variables for repo
      uses: BuoySoftware/github-actions/setup-env@main
      with:
        env_vars: ${{ inputs.env_vars }}
        working_directory: ${{ inputs.working_directory }}

    - name: Install Ruby for repo
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working_directory }}

    - name: Get node version
      id: repo_node_vers
      run: echo "v=$(grep 'nodejs' ${{ inputs.node_version_file }} | awk '{print $2}')" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Install Node
      uses: BuoySoftware/github-actions/setup-node@main
      with:
        node-version: ${{ steps.repo_node_vers.outputs.v }}
        github_packages_token: ${{ inputs.github_packages_token }}
        working-directory: ${{ inputs.working_directory }}

    - name: bundle check for repo
      run: bundle check
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Create, load and seed repo database
      run: bundle exec rake db:drop db:create db:schema:load ${{ inputs.extra_rake_tasks }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Precompile test assets
      uses: BuoySoftware/github-actions/precompile-assets@main
      with:
        github_sha: ${{ env.repo_sha }}
        working-directory: ${{ inputs.working_directory }}

    - name: Add tmp/pids folder
      run: |
        if [ ! -d tmp/pids ]; then
          mkdir -p tmp/pids
        fi
      shell: bash
      working-directory: ${{ inputs.working_directory }}
