name: 'Release Prep'
description: 'Prepares a release by comparing base and head refs'

inputs:
  base_ref:
    description: 'The base reference to compare against'
    required: true
  head_ref:
    description: 'The head reference to compare'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'latest'
        bundler: 'latest'
        bundler-cache: true
        working-directory: './release-prep'

    - name: Install dependencies
      shell: bash
      working-directory: './release-prep'
      run: bundle install

    - name: Run Release Prep
      shell: bash
      working-directory: './release-prep'
      run: bundle exec ./bin/release_prep --base-ref="${{ inputs.base_ref }}" --head-ref="${{ inputs.head_ref }}" 
