name: Cache playwright browsers

runs:
  using: "composite"

  - name: Store playwright version
    run: |
      pw_version=$(yarn info @playwright/test -A --json | jq -r '.data.version')
      echo "Playwright version: $pw_version"
      echo "PLAYWRIGHT_VERSION=$pw_version" >> $GITHUB_ENV
    shell: bash

  - name: Cache playwright browsers by playwright version
    id: cache-playwright-browsers
    uses: actions/cache@v4
    with:
      path: ~/.cache/ms-playwright
      key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

  - name: Install Playwright Browsers
    if: ${{ steps.cache-playwright-browsers.outputs.cache-hit != 'true' }}
    run: yarn playwright install chromium --with-deps
    shell: bash
