name: Cache playwright browsers
description: Cache playwright browsers by os and playwright version

inputs:
  with_webkit:
    default: "false"
    description: Whether to install webkit browsers
    required: false
    type: boolean

runs:
  using: "composite"

  steps:
    - name: Store playwright version
      run: |
        pw_version=$(jq -r '.devDependencies["@playwright/test"] // .dependencies["@playwright/test"]' package.json | tr -d '^~')
        echo "Playwright version: $pw_version"
        echo "PLAYWRIGHT_VERSION=$pw_version" >> $GITHUB_ENV
      shell: bash

    - name: Cache playwright browsers by playwright version
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Browsers
      if: ${{ steps.cache-playwright-browsers.outputs.cache-hit != 'true' }}
      run: |
        yarn playwright install chromium --with-deps
      shell: bash

    - name: Install Webkit Browsers
      if: ${{ inputs.with_webkit == 'true' }}
      run: |
        yarn playwright install webkit --with-deps
      shell: bash
