name: Set env file

inputs:
  env_vars:
    default: ""
    description: Environment variables to set
    required: false
    type: string
  working_directory:
    default: "."
    description: Desired working directory for the repository
    required: false
    type: string

runs:
  using: "composite"

  steps:
    - name: Set up environment variable file
      run: |
        # Store environment variables in a .env file
        printf '%s\n' "${{ inputs.env_vars }}" >> .env
      shell: bash
      working-directory: ${{ inputs.working_directory }}
