name: Set env file

inputs:
  env_vars:
    default: ""
    description: Environment variables to set
    required: false
    type: string
  replace_vars_with_lvh_host:
    default: ""
    description: Space delimited list of environment variables to replace localhost with lvh.me
    required: false
    type: string
  working_directory:
    default: "."
    description: Desired working directory for the repository
    required: false
    type: string

runs:
  using: "composite"

  steps:
    - name: Set up environment variable file
      run: |
        # Create a placeholder file to store the environment variables
        printf '%s\n' "${{ inputs.env_vars }}" >> placeholder.txt

        # Use lvh.me as the host for specific environment variables
        ARRAY=(${{ inputs.replace_vars_with_lvh_host }})
        for i in "${ARRAY[@]}"
        do
          sed -r -i -E "s/($i=.*)localhost/\1lvh.me/" placeholder.txt
        done

        # Copy placeholder.txt into .env.sample and create a new .env file
        awk -F= '{a[$1]=$2}END{for(i in a) print i "=" a[i]}' .env.sample placeholder.txt > .env

        # Cleanup the .env file
        sed -r -i -E '/^[[:blank:]]*#/d;s/#.*//' .env
        sed -r -i -E 's/^=//' .env
        sort .env -o .env
      shell: bash
      working-directory: ${{ inputs.working_directory }}
