name: Build docker image
description: Build and push Docker images to ECR

inputs:
  ecr_repository:
    description: ECR repo to push image
    required: false
  aws_access_key_id:
    description: AWS ECR access key id
    required: true
  aws_secret_access_key:
    description: AWS ECR secret access key
    required: true
  build_args:
    description: Additional docker build args
  slack_webhook_url:
    description: Slack webhook URL for notifications
    required: false

outputs:
  ref_tag:
    description: "Ref tag assigned to the image"
    value: ${{ steps.current-git-details.outputs.tag }}
  registry:
    description: "ECR registry for the image"
    value: ${{ steps.login-ecr.outputs.registry }}
  short_sha_tag: 
    description: "Short SHA tag assigned to the image"
    value: ${{ steps.current-git-details.outputs.short }}

runs:
  using: "composite"

  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Read current git details
      id: current-git-details
      shell: bash
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "short=sha-${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "long=sha-$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "tag=tag-${{ github.ref_name }}" >> $GITHUB_OUTPUT
          
          # Create unique trace tag with SHORT_SHA and datetime
          DATETIME=$(date -u +"%Y%m%d-%H%M%S")
          TRACE="trace-sha-${SHORT_SHA}-${DATETIME}"
          echo "trace=${TRACE}" >> $GITHUB_OUTPUT
        else
          echo "tag=" >> $GITHUB_OUTPUT
          echo "trace=" >> $GITHUB_OUTPUT
        fi

    - name: Configure Amazon ECR Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Check if the image already exists
      id: check-image-exists
      shell: bash
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.ecr_repository }}
        SHORT_SHA_TAG: ${{ steps.current-git-details.outputs.short }}
        REF_TAG: ${{ steps.current-git-details.outputs.tag }}
        TRACE_TAG: ${{ steps.current-git-details.outputs.trace }}
      run: |
        if [[ -n "$REF_TAG" ]]; then
          REF_IMAGE_EXISTS=$(docker manifest inspect $REGISTRY/$REPOSITORY:$REF_TAG > /dev/null 2>&1 && echo yes || echo no)

          if [[ "$REF_IMAGE_EXISTS" == "yes" ]]; then
            echo "Ref tag image already exists, skipping build step"
            echo "image_exists=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Ref tag image not found, building fresh image"
            echo "image_exists=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi

        # For non tagged builds, check if we need to build a new image
        SHORT_IMAGE_EXISTS=$(docker manifest inspect $REGISTRY/$REPOSITORY:$SHORT_SHA_TAG > /dev/null 2>&1 && echo yes || echo no)
        if [[ "$SHORT_IMAGE_EXISTS" == "yes" ]]; then
          echo "Image already exists, skipping build step"
          echo "image_exists=true" >> $GITHUB_OUTPUT
        else
          echo "Image not found, proceeding with build step"
          echo "image_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Build, tag, and push docker image to Amazon ECR
      if: steps.check-image-exists.outputs.image_exists == 'false'
      shell: bash
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.ecr_repository }}
        SHORT_SHA_TAG: ${{ steps.current-git-details.outputs.short }}
        LONG_SHA_TAG: ${{ steps.current-git-details.outputs.long }}
        REF_TAG: ${{ steps.current-git-details.outputs.tag }}
        TRACE_TAG: ${{ steps.current-git-details.outputs.trace }}
        BUILD_ARGS: ${{ inputs.build_args }}
      run: |
          # For tagged builds, use ref and trace tags
          if [ -n "$REF_TAG" ]; then
            TAGS="-t $REGISTRY/$REPOSITORY:$REF_TAG -t $REGISTRY/$REPOSITORY:$TRACE_TAG"
            echo "Building with ref tag: $REF_TAG and trace tag: $TRACE_TAG"
          else
            # For non-tagged builds, use SHA tags
            TAGS="-t $REGISTRY/$REPOSITORY:$SHORT_SHA_TAG -t $REGISTRY/$REPOSITORY:$LONG_SHA_TAG"
            echo "Building with SHA tags: $SHORT_SHA_TAG, $LONG_SHA_TAG"
          fi

          docker build . $TAGS $BUILD_ARGS --build-arg CURR_GIT_SHA=$LONG_SHA_TAG
          docker push --all-tags $REGISTRY/$REPOSITORY

    - name: Notify Slack on failure
      if: failure() && inputs.slack_webhook_url != ''
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        AS_REF: ${{ github.ref }}
        AS_AUTHOR: ${{ github.actor }}
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            "attachments": [{
              "color": "danger",
              "mrkdwn_in": ["text"],
              "text": ":x: *Docker build failed*\n*Ref:* ${{ env.AS_REF }}\n*Author:* ${{ env.AS_AUTHOR }}\n\nPlease check the CI job logs for details: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
            }]
          }
